"""empty message

Revision ID: 9ffc733fb2ec
Revises: ae1cf1fc33aa
Create Date: 2022-10-07 11:30:52.198071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffc733fb2ec'
down_revision = 'ae1cf1fc33aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
